server:
  port: 8081
 
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: API Gateway
    
  cloud:
    gateway:
      routes:
      - id: Event
        uri: http://localhost:8091
        predicates:
        - Path=/event/**
        
        
      - id: Ticket
        uri: http://localhost:8092
        predicates:
        - Path=/ticket/**
        
      - id: Venue
        uri: http://localhost:8093
        predicates:
        - Path=/venue/**
        
      - id: Authentication-Service
        uri: http://localhost:8095
        predicates:
        - Path=/api/**
        
       