server:
  port: 8081
 
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: API Gateway
    
  cloud:
    gateway:
      routes:
      - id: Event
        uri: http://localhost:8091
        predicates:
        - Path=/event/**